apiVersion: v1
kind: Service
metadata:
  name: spot-render-web-stable
  namespace: spot-render
spec:
  selector:
    app: spot-render-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: spot-render-web-canary
  namespace: spot-render
spec:
  selector:
    app: spot-render-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
